Subject: login & telnetd editing/message ignore gettytab, ftp lacks PASV, chflags(1) source and chflags(2) manpage typos, rcmd(3) & rexec(3) have accept(2)/connect(2) usage Index:	 src/bin/login/Makefile,login.c src/ucb/ftp/* src/libexec/telnetd/Makfile,telnetd.c src/libexec/getty/gettytab.{c,h} src/lib/libc/net/{rcmd,rexec}.c
Description:
	1)
	--
	The patch for login makes login use gettytab.  Login used to set the
	local editing mode to a hardcoded 0, and second, if you specify
	a non-standard login prompt string in gettytab (lm), it was used
	by getty as the initial login prompt, but if you hit an incorrect
	password, login issued the next login prompt which did not use
	the value from gettytab.

	Also, telnet always had login issue the login prompt, so from
	there, the lm value in gettytab was never used. Now this should
	be proper no matter where you come from, or which login attempt it is.

	The local editing setting affected both telnet connections, and
	repeated login prompts by login. Since local mode was hardcoded
	to 0, any attempt at editing the username written at the login
	prompt was not echoed correctly when editing (basically, any
	delete would do the delete internally, but visually nothing showed).

	2)
	--
	ftp(1), the client, lacks the 'passive' command.  ftpd(8), the
	server, does have support for passive mode.

	3)
	--
	The chflags(1) source has the incorrect name/sccsid block at the
	beginning of the file.

	4)
	--
	chflags(2)  manpage has an incorrect flag name

	5)
	--
	rexec(3) and rcmd(3) call accept(2) and connect(2) with incorrect
	number of arguments.

Repeat-By:
	1)
	--
	For lm, try setting a different login message, and connect on a normal
	serial line. Observe that the different login prompt is used. Enter a
	username and password that isn't valid, and note that the next prompt
	will say "login: " no matter what was specified using lm in gettytab.
	For telnet, just connect and observe that "login: " is always prompted,
	no matter what value is set in gettytab.

	For the editing try to connect over a serial line and enter a username
	and delete characters again, and observe that they will get visually
	deleted as well. Enter an invalid username and password, and at the next
	login: prompt enter a username and try to delete characters. Observe
	that nothing is shown indicating which characters have been deleted.
	Or do the same using telnet.

	With this patch, both those problems are now addressed. In addition,
	another class  in gettytab will be searched for by login, named "login".
	The default class is always applied first, but things can then be
	overridden or extended by the login class. For editing to work as
	expected, it is recommended that "cb" and "ce" are added to the default
	class.

	telnetd had made a copy of the gettytab sources.  The same copy
	was proposed for login.  The idea of having 3 copies of the same
	gettytab parsing code in the system is bad.  Changes have been
	made in the telnetd and login Makefile to use the VPATH macro and
	refer to the getty source directory.

	2)
	--
[curlyjoe:~] sms% rlogin vernon
ftp localhost
Connected to LOCALHOST.2bsd.com.
220 vernon.2bsd.com FTP server (Version 5.83 Sat Oct 26 15:17:31 PDT 1996) ready.
Name (localhost:sms):
331 Password required for sms.
Password:
230 User sms logged in.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> passive
?Invalid command
ftp> quit
221 Goodbye.

	3)
	--
	Observation.  When I created chflags.c I copied a template file
	to edit and forgot to change the header from symcompact.c to chflags.c

	4)
	--
	man 2 chflags

	Note "ARCHIVE" is used instead of "SF_ARCHIVE" for the archive flag.

	5)
	--
	Compile rcmd.c / rexec.c on a system that has a strict compiler:
rcmd.c:78:47: error: too many arguments to function call, expected 3, have 4

	The same thing happens for the use of connect().

	lint will catch this on a 2.11BSD system with the message

connect: variable # of args.    /usr/share/lint/llib-lc(54)  ::  rcmd.c(76)

Fix:
	The login/telnetd/getty Description, Repeat-By and patch provided
	by bqt@softjar.se

	Cut where indicated and save to a file (/tmp/487.patch).  Then:

cd /
patch -p0 < /tmp/487.patch

cd /usr/src/lib/libc/net
make rcmd.o rexec.o
ar rv /lib/libc.a rexec.o rcmd.o
ranlib /lib/libc.a
cd profiled
ar rv /usr/lib/libc_p.a rexec.o rcmd.o
ranlib /usr/lib/libc_p.a
cd ..
make clean

cd /usr/src/bin/login
make install
make clean

cd /usr/src/libexec/telnetd
make install
make clean
rm gettytab.c gettytab.h init.c subr.c

cd /usr/src/libexec/getty
make install
make clean

cd /usr/src/man/man2
make chflags.0
install -o bin -g bin -m 444 chflags.0 /usr/man/cat2

cd /usr/src/ucb/ftp
make install
make clean

	This and previous updates to 2.11BSD are available at the following
	locations:

	ftp://ftp.dfupdate.se/pub/pdp11/2.11BSD
	https://www.tuhs.org/Archive/Distributions/UCB/2.11BSD/Patches/
	ftp://ftp.2bsd.com/2.11BSD
	http://www.2bsd.com/2.11BSD